services:
  mongo:
    image: aws1artifactory1.absolute.com:443/dockerio-remote/mongo:7.0.6
    logging:
      driver: none
    ports:
      - "27017:27017"
    healthcheck:
      # simply wait for 20 seconds
      # replace with your health-check cmd if you have one
      test: [ "CMD", "sleep", "20" ]
      interval: 5s
      timeout: 25s
      retries: 1
      start_period: 5s
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=FangIncomeDaily
    volumes:
      - ./develop/init-mongodb:/docker-entrypoint-initdb.d


#  mongo-express:
#    image: mongo-express
#    container_name: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME:root
#      - ME_CONFIG_MONGODB_ADMINPASSWORD:password
#      - ME_CONFIG_MONGODB_SERVER=mongodb
##      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/

#volumes:
#  data: {}
#networks:
#  default:
#    name: mongodb_network
